/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SenhaImport } from './routes/Senha'
import { Route as ChamadasImport } from './routes/Chamadas'
import { Route as AdminImport } from './routes/Admin'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SenhaRoute = SenhaImport.update({
  id: '/Senha',
  path: '/Senha',
  getParentRoute: () => rootRoute,
} as any)

const ChamadasRoute = ChamadasImport.update({
  id: '/Chamadas',
  path: '/Chamadas',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/Admin',
  path: '/Admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Admin': {
      id: '/Admin'
      path: '/Admin'
      fullPath: '/Admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/Chamadas': {
      id: '/Chamadas'
      path: '/Chamadas'
      fullPath: '/Chamadas'
      preLoaderRoute: typeof ChamadasImport
      parentRoute: typeof rootRoute
    }
    '/Senha': {
      id: '/Senha'
      path: '/Senha'
      fullPath: '/Senha'
      preLoaderRoute: typeof SenhaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Admin': typeof AdminRoute
  '/Chamadas': typeof ChamadasRoute
  '/Senha': typeof SenhaRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Admin': typeof AdminRoute
  '/Chamadas': typeof ChamadasRoute
  '/Senha': typeof SenhaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Admin': typeof AdminRoute
  '/Chamadas': typeof ChamadasRoute
  '/Senha': typeof SenhaRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Admin' | '/Chamadas' | '/Senha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Admin' | '/Chamadas' | '/Senha'
  id: '__root__' | '/' | '/Admin' | '/Chamadas' | '/Senha'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChamadasRoute: typeof ChamadasRoute
  SenhaRoute: typeof SenhaRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChamadasRoute: ChamadasRoute,
  SenhaRoute: SenhaRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Admin",
        "/Chamadas",
        "/Senha"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Admin": {
      "filePath": "Admin.tsx"
    },
    "/Chamadas": {
      "filePath": "Chamadas.tsx"
    },
    "/Senha": {
      "filePath": "Senha.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
